# vim: ts=1:sts=2:sw=2:expandtab

version: '3'

services:
  bitwarden:
    image: mprasil/bitwarden:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/data/bitwarden:/data/
    environment:
      - YUBICO_CLIENT_ID=$YUBICO_CLIENT_ID
      - YUBICO_SECRET_KEY=$YUBICO_SECRET_KEY
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=bitwarden.serubin.net"
      - "traefik.frontend.rule=Host: bitwarden.serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"

networks:
  traefik-public:
    external: true
