# vim: ts=1:sts=2:sw=2:expandtab

version: '3'

services:
  bitwarden:
    image: mprasil/bitwarden:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/data/bitwarden:/data/
    env_file:
      - yubico.env
    networks:
      - default
      - service-default
    labels:
      - "traefik.enable=true"
      - "traefik.domain=bitwarden.serubin.net"
      - "traefik.frontend.rule=Host: bitwarden.serubin.net"
      - "traefik.docker.network=service-default"
      - "traefik.port=80"

networks:
  service-default:
    external: true
